#    G:\pail_oil_cta\results\xgb_top5_20260320_113951\backtest_combo_1\backtest_params.json ^
#    G:\pail_oil_cta\results\xgb_top5_20260320_113951\backtest_combo_3\backtest_params.json ^
#    G:\pail_oil_cta\results\xgb_top5_20260320_153151\backtest_combo_5\backtest_params.json^
#    G:\pail_oil_cta\results\xgb_top5_20260320_153151\backtest_combo_3\backtest_params.json^
#    G:\pail_oil_cta\results\top5_20260320_184721\backtest_combo_1\backtest_params.json
#    G:\pail_oil_cta\results\xgb_top5_20260320_211908\backtest_combo_2\backtest_params.json
#    G:\pail_oil_cta\results\top5_20260320_162332\backtest_combo_1\backtest_params.json
#G:\pail_oil_cta\results\top5_20260324_130920\backtest_combo_1\backtest_params.json
#G:\pail_oil_cta\results\top5_20260324_130920\backtest_combo_2\backtest_params.json
G:\pail_oil_cta\results\top5_20260324_215644\backtest_combo_1\backtest_params.json
G:\pail_oil_cta\results\top5_20260324_215644\backtest_combo_2\backtest_params.json
G:\pail_oil_cta\results\top5_20260324_215644\backtest_combo_3\backtest_params.json
#G:\pail_oil_cta\results\top5_20260324_215644\backtest_combo_4\backtest_params.json
G:\pail_oil_cta\results\top5_20260324_215644\backtest_combo_5\backtest_params.json


#G:\pail_oil_cta\results\top5_20260324_130920\backtest_combo_4\backtest_params.json   
#G:\pail_oil_cta\results\top5_20260324_130920\backtest_combo_5\backtest_params.json
#G:\pail_oil_cta\results\xgb_top5_20260324_145826\backtest_combo_2\backtest_params.json
#G:\pail_oil_cta\results\xgb_top5_20260324_143940\backtest_combo_1\backtest_params.json
    # G:\pail_oil_cta\results\top5_20260320_184721\backtest_combo_4\backtest_params.json
                                                                                                                                     
    # G:\pail_oil_cta\results\top5_20260320_162332\backtest_combo_2\backtest_params.json
